apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    application: node-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      application: node-app
  template:
    metadata:
      labels:
        application: node-app
    spec:
      containers:
        - name: node-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: debug
              containerPort: 9229
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
