apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    application: node-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    application: node-app
